import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  img1: {
    width: 20,
    height: 20,
    tintColor: '#e5e5e5',
  },
  addMenuBtn: {
    marginRight: 10,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  view1: {
    backgroundColor: '#2B3252',
    flex: 1,
  },
  view2: {
    width: '95%',
    borderBottomWidth: 0.5,
    borderColor: 'gray',
    marginTop: 10,
    alignSelf: 'center',
  },
  view3: {
    width: '100%',
    height: 20,
  },
  view4: {
    width: '100%',
    height: '45%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#465185',
  },
  view5: {
    height: '100%',
    width: '45%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view6: {
    height: 60,
    width: '95%',
    marginTop: 20,
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
  },
  Starview: {
    height: 20,
    width: 20,
    position: 'absolute',
    right: 15,
    top: 0,
  },
  line1: {
    width: 1,
    height: '100%',
    backgroundColor: 'gray',
    marginLeft: '2%',
    marginRight: '2%',
  },
  text1: {
    color: '#e5e5e5',
    fontSize: 19,
    fontWeight: '700',
  },
  text2: {
    color: '#e5e5e5',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 5,
    marginBottom: 10,
  },
  text3: {
    color: '#e5e5e5',
    fontSize: 16,
    fontWeight: '600',
  },
  text4: {
    color: '#e5e5e5',
    fontSize: 17,
    fontWeight: '400',
  },
  text10: {
    color: '#D5A253',
    fontSize: 17,
    fontWeight: '400',
    marginLeft: 30,
    width: 200,
  },
  text5: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 5,
    marginTop: 15,
  },
  text6: {
    color: '#e5e5e5',
    fontSize: 20,
    fontWeight: '700',
  },
  text7: {
    color: '#D5A253',
    fontSize: 17,
    fontWeight: '600',
  },
  saveBtn1: {
    height: 45,
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    marginTop: 30,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  cancleBtn1: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 20,
  },
  cancleBtn1text: {
    color: '#e5e5e5',
    fontSize: 20,
    fontWeight: '800',
  },
  input1: {
    height: 50,
    width: '90%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    fontSize: 18,
    marginTop: 10,
    color: '#e5e5e5',
  },
  input2: {
    height: 100,
    width: '90%',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    textAlignVertical: 'top',
    fontSize: 18,
    borderRadius: 5,
    color: '#e5e5e5',
  },
  checkbox: {
    width: '95%',
    marginTop: 10,
  },
  checkboxtext: {
    fontSize: 18,
    color: '#E5E5E5',
    marginBottom: 10,
    marginTop: 10,
  },
  img2: {
    width: 25,
    height: 25,
    tintColor: '#936A4A',
  },
  img3: {
    width: 30,
    height: 30,
  },
  swipeoutSide: {
    backgroundColor: '#fff',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  view20: {
    width: '90%',
    flexDirection: 'row',
    marginTop: 5,
  },
  input4: {
    height: 40,
    width: '100%',
    fontSize: 16,
    color: '#E5E5E5',
  },
  view12: {
    width: '95%',
    marginTop: 20,
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
    height: 90,
  },
  text33: {
    color: '#D5A253',
    fontSize: 17,
    fontWeight: '600',
  },
  input3: {
    width: '100%',
    marginTop: 5,
    fontSize: 16,
    color: '#E5E5E5',
    height: 55,
  },
});
