import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },
  view2: {
    height: '7%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view3: {
    height: '80%',
    width: '90%',
    backgroundColor: '#E5E5E5',
    flexDirection: 'row',
    borderRadius: 5,
  },
  view4: {
    height: '7%',
    width: '100%',
    flexDirection: 'row',
  },
  view5: {
    height: '100%',
    width: '25%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view6: {
    width: '100%',
  },
  view7: {
    width: '95%',
    backgroundColor: '#2b3252',
    // height: 160,
    marginBottom: 10,
    borderRadius: 5,
    alignSelf: 'center',
    borderWidth: 0.5,
    borderColor: 'gray',
    shadowOffset: { width: 5, height: 5 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  view8: {
    width: '100%',
    height: 50,
    marginTop: 5,
    flexDirection: 'row',
  },
  view9: {
    width: '80%',
    height: 50,
    marginLeft: 10,
  },
  view10: {
    width: '100%',
    height: 40,
    marginTop: 5,
    flexDirection: 'row',
  },
  view11: {
    height: 180,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view12: {
    height: 100,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: '15%',
    flexDirection: 'row',
  },
  // minusBtn: {
  //   color: 'gray',
  //   fontSize: 50,
  //   fontWeight: '600',
  // },
  // PlusBtn: {
  //   color: 'gray',
  //   fontSize: 40,
  //   fontWeight: '600',
  // },
  view13: {
    height: 180,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view14: {
    height: 180,
    width: '100%',
    flexDirection: 'row',
  },
  view15: {
    height: 60,
    width: 220,
    backgroundColor: 'white',
    shadowColor: 'gray',
    shadowOpacity: 3,
    shadowRadius: 3,
    shadowOffset: {
      height: 3,
      width: 3,
    },
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: 'gray',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view16: {
    height: 120,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view17: {
    position: 'absolute',
    right: '1%',
    top: '1%',
  },
  view18: {
    height: 50,
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#936A4A',
    borderRadius: 30,
    zIndex: 1,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  view19: {
    marginTop: 30,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  view20: {
    height: 180,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view30: {
    height: 130,
    width: '100%',
    backgroundColor: '#FF5F5F',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  redeemView: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 5,
    marginTop: 5,
  },
  choseBtn1: {
    height: 50,
    width: 150,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chosetext: {
    color: '#E5E5E5',
    fontSize: 18,
    fontWeight: '600',
  },
  img1: {
    height: 20,
    width: 20,
    marginTop: 12,
    marginLeft: 7,
    tintColor: '#A3A3A3',
  },
  img2: {
    height: 25,
    width: 25,
    marginTop: 6,
    marginLeft: 5,
    tintColor: '#936A4A',
  },
  img3: {
    height: 20,
    width: 20,
    tintColor: '#E5E5E5',
  },
  img4: {
    height: 25,
    width: 25,
  },
  img5: {
    height: 60,
    width: 60,
  },
  input1: {
    height: '100%',
    width: '90%',
    marginLeft: 5,
    fontSize: 15,
    color: 'black',
  },
  input2: {
    height: 50,
    width: '80%',
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    marginTop: 20,
    textAlign: 'center',
    alignSelf: 'center',
    color: '#E5E5E5',
    fontSize: 18,
  },
  text1: {
    color: '#E5E5E5',
    fontSize: 17,
    fontWeight: '700',
  },
  text2: {
    color: '#E5E5E5',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 10,
    marginLeft: 10,
    marginBottom: 5,
  },
  text3: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    marginLeft: 5,
    marginTop: 5,
  },
  text33: {
    color: '#B22222',
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 5,
    marginTop: 5,
  },
  text4: {
    color: '#E5E5E5',
    fontSize: 16,
    fontWeight: '500',
    marginTop: 5,
  },
  text5: {
    color: '#E5E5E5',
    fontSize: 16,
    fontWeight: '500',
    marginTop: 10,
  },
  text6: {
    color: 'gray',
    fontSize: 20,
    fontWeight: '600',
    position: 'absolute',
    top: '15%',
  },
  text7: {
    color: '#FF5F5F',
    fontSize: 50,
    fontWeight: '800',
    marginLeft: '10%',
    marginRight: '10%',
  },
  text8: {
    color: '#FF5F5F',
    fontSize: 22,
    fontWeight: '800',
    marginLeft: '10%',
    marginRight: '10%',
  },
  text9: {
    color: '#FF5F5F',
    fontSize: 18,
    fontWeight: '800',
  },
  text12: {
    fontSize: 22,
    color: '#FF5F5F',
    fontWeight: '800',
  },
  text13: {
    fontSize: 20,
    color: '#D5A253',
    fontWeight: '700',
    marginTop: 20,
  },
  text23: {
    fontSize: 25,
    color: '#D5A253',
    fontWeight: '700',
    marginTop: 10,
  },
  text24: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '600',
    marginTop: 10,
  },
  text14: {
    color: '#E5E5E5',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 20,
  },
  text15: {
    color: '#D5A253',
    fontSize: 40,
    fontWeight: '800',
    marginLeft: '10%',
    marginRight: '10%',
  },
  line1: {
    height: 2,
    width: '100%',
    backgroundColor: '#D5A253',
    position: 'absolute',
    bottom: '0%',
  },
  line2: {
    height: 1,
    width: '80%',
    backgroundColor: '#D5A253',
    alignSelf: 'center',
    marginTop: 15,
  },
  confirmBtn: {
    height: 50,
    width: '45%',
    backgroundColor: '#fa7883',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    borderRadius: 5,
    marginRight: '2.5%',
  },
  confirmBtn1: {
    height: 50,
    width: 150,
    backgroundColor: '#fa7883',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    borderRadius: 5,
    marginRight: '2.5%',
  },
  confirmBtntext: {
    color: '#E5E5E5',
    fontSize: 18,
    fontWeight: '700',
  },
  rectButton: {
    flex: 1,
    height: '100%',
    paddingVertical: 10,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  inprocessBtn: {
    borderRadius: 45,
    alignItems: 'center',
    justifyContent: 'center',
    height: 30,
    backgroundColor: '#936A4A',
    shadowOffset: { width: 5, height: 5 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    //elevation: 8,
  },
  NoShowBtn: {
    borderRadius: 45,
    alignItems: 'center',
    justifyContent: 'center',
    height: 30,
    width: 90,
    backgroundColor: '#936A4A',
    marginLeft: 5,
    shadowOffset: { width: 5, height: 5 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    //elevation: 8,
  },
  view21: {
    position: 'absolute',
    right: 5,
    top: 5,
    height: 70,
  },
  EditButton1: {
    height: 25,
    width: 25,
    marginTop: 10,
    position: 'absolute',
    right: 5,
    bottom: 0,
  },
  inprocessBtntext: {
    color: '#E5E5E5',
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 10,
    marginRight: 10,
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  CancleboostItemModel: {
    position: 'absolute',
    right: 0,
    marginTop: 0,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 15,
  },
  CancleboostItemModeltext: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '800',
  },
  minusBtn: {
    color: '#E5E5E5',
    fontSize: 35,
    fontWeight: '800',
  },
  minusBtn1: {
    color: '#9F9F9FF8',
    fontSize: 35,
    fontWeight: '800',
  },
  PlusBtn: {
    color: '#E5E5E5',
    fontSize: 35,
    fontWeight: '800',
  },
  PlusBtn1: {
    color: '#9F9F9FF8',
    fontSize: 35,
    fontWeight: '800',
  },
  timePickerStyle: {
    backgroundColor: '#2B3252',
    width: '70%',
    borderTopWidth: 1,
    borderColor: 'gray',
    position: 'absolute',
    bottom: 20,
  },
  timePickerStyle1: {
    //height: 220,
    width: '100%',
    borderTopWidth: 1,
    borderColor: 'gray',
  },
  NoAvailableTime: {
    color: '#ED2939',
    fontSize: 18,
    fontWeight: '600',
  },
  donebtnText: {
    color: '#FF5F5F',
    fontSize: 20,
    fontWeight: '800',
  },
  donebtn: {
    width: 60,
    height: 30,
    marginTop: 10,
    marginLeft: 10,
  },
  donebtn1: {
    width: 60,
    height: 30,
    marginTop: 10,
    marginLeft: 10,
  },
  donebtnText1: {
    color: '#936A4A',
    fontSize: 20,
    fontWeight: '800',
  },
  confirmBtn2: {
    height: 45,
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    alignSelf: 'center',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  confirmBtn3: {
    height: 40,
    width: '50%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    alignSelf: 'center',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  pickerStyle: {
    width: '100%',
    color: '#344953',
    justifyContent: 'center',
  },
  pickerStyle1: {
    width: '100%',
    color: 'white',
    justifyContent: 'center',
  },
});
