import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },
  view3: {
    width: 120,
    height: 120,
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'gray',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view4: {
    height: 60,
    width: '95%',
    marginTop: 20,
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
  },
  img1: {
    width: '90%',
    height: '90%',
    borderRadius: 55,
    alignSelf: 'center',
  },
  plusBtn: {
    position: 'absolute',
    right: '0%',
    bottom: -10,
  },
  plusBtntext: {
    fontSize: 50,
    fontWeight: '800',
    color: '#936A4A',
  },

  input1: {
    height: 50,
    width: '90%',
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
    fontSize: 18,
    marginTop: 20,
    textAlign: 'center',
    color: '#E5E5E5',
  },
  input4: {
    height: 40,
    width: '100%',
    fontSize: 16,
    color: '#E5E5E5',
  },
  text1: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    alignSelf: 'center',
    textAlign: 'center',
    width: '70%',
    marginTop: 20,
  },
  text2: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    width: '70%',
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 10,
  },
  text3: {
    color: '#D5A253',
    fontSize: 17,
    fontWeight: '600',
  },
  text7: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 20,
    textAlign: 'center',
  },
  input2: {
    height: 50,
    width: '90%',
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
    fontSize: 18,
    marginTop: 10,
    textAlign: 'center',
    color: '#E5E5E5',
  },
  nextBtn: {
    height: 50,
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 50,
    marginBottom: 20,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  nextBtntext: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '700',
  },
  checkbox2: {
    width: '100%',
    marginLeft: 10,
    marginTop: 10,
  },
  img2: {
    width: 30,
    height: 30,
    tintColor: '#936A4A',
  },
  btnsave: {
    height: 45,
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 20,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  checkboxtext2: {
    color: '#E5E5E5',
    fontSize: 18,
    fontWeight: '600',
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  cancleBtn1: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancleBtn1text: {
    color: '#e5e5e5',
    fontSize: 25,
    fontWeight: '800',
  },
  SaveBtntext: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '500',
    marginRight: 10,
  },
});
