import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },
  view2: {
    width: '100%',
  },

  view3: {
    width: '100%',
  },
  view4: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#2B3252',
  },
  view5: {
    width: '48%',
    marginRight: 10,
    borderBottomWidth: 0.5,
    borderColor: '#D5A253',
  },
  view6: {
    width: '95%',
    alignSelf: 'center',
    marginTop: 10,
  },
  view7: {
    width: '90%',
    marginTop: 30,
    flexDirection: 'row',
  },
  view8: {
    width: '45%',
    marginRight: '5%',
    borderBottomWidth: 0.5,
    borderColor: '#D5A253',
  },
  view9: {
    width: '100%',
    flexDirection: 'row',
  },
  view10: {
    height: '100%',
    width: '100%',
  },
  text1: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '600',
  },
  text2: {
    color: '#E5E5E5',
    fontSize: 17,
    fontWeight: '700',
    marginTop: 5,
  },
  text3: {
    color: '#E5E5E5',
    fontSize: 16,
    fontWeight: '500',
    marginTop: 5,
    marginBottom: 5,
  },
  text4: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '700',
    marginTop: 15,
  },
  text5: {
    color: '#E5E5E5',
    fontSize: 17,
    fontWeight: '700',
    marginTop: 5,
  },
  btn1: {
    position: 'absolute',
    right: 10,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  img1: {
    width: 18,
    height: 18,
    tintColor: '#936A4A',
    marginBottom: 5,
  },
  img2: {
    width: 20,
    height: 20,
    tintColor: '#936A4A',
  },
  CancleboostItemModel: {
    position: 'absolute',
    right: 0,
    marginTop: 0,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 20,
  },
  CancleboostItemModeltext: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '800',
  },
  input1: {
    height: 40,
    width: '70%',
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 10,
    color: '#E5E5E5',
  },
  btn2: {
    height: 45,
    width: '60%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    alignSelf: 'center',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    marginBottom: 50,
  },
  btn3: {
    height: 45,
    width: '60%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    alignSelf: 'center',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    marginBottom: 50,
  },
  btn2text: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '700',
  },
  checkbox: {
    width: '90%',
    marginTop: 20,
  },
  checkboxtext: {
    color: '#E5E5E5',
    fontSize: 16,
    fontWeight: '600',
  },
  leftSwip: {
    backgroundColor: 'white',
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
});