import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },

  view2: {
    height: 60,
    width: '100%',
    flexDirection: 'row',
  },
  view3: {
    height: '100%',
    width: '38%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view33: {
    height: '100%',
    width: '24%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view4: {
    height: 150,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  view5: {
    height: 70,
    width: '100%',
    alignSelf: 'center',
    marginTop: 50,
    flexDirection: 'row',
  },
  view17: {
    height: 70,
    width: '90%',
    alignSelf: 'center',
    marginTop: 40,
    flexDirection: 'row',
  },
  view6: {
    height: '100%',
    width: '48.5%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view7: {
    height: '100%',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view8: {
    height: 50,
    width: '100%',
    backgroundColor: '#d0cece',
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view9: {
    height: 60,
    width: '45%',
    //backgroundColor: "#fa7883",
    alignItems: 'center',
    justifyContent: 'center',
    // borderWidth:1,
    marginLeft: '2.5%',
  },
  view10: {
    width: '100%',
    marginTop: 20,
    // marginTop: 10,
    flex: 1,
    marginBottom: 60,
  },
  view16: {
    width: '100%',
    marginTop: 10,
    flex: 1,
    marginBottom: 60,
  },
  view11: {
    width: '95%',
    marginTop: 10,
    borderBottomWidth: 0.5,
    borderColor: '#D5A253',
    flexDirection: 'row',
    alignSelf: 'center',
  },
  view12: {
    height: '100%',
    flexDirection: 'row',
    width: '15%',
    position: 'absolute',
    right: 5,
  },
  view13: {
    width: '85%',
    height: '100%',
  },
  view14: {
    width: '95%',
    borderBottomWidth: 0.5,
    borderColor: '#D5A253',
    flexDirection: 'row',
    alignSelf: 'center',
  },
  view15: {
    width: '100%',
    height: '100%',
  },
  view19: {
    width: '100%',
    height: '100%',
  },
  ifnotMenu: {
    width: '100%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  CountView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },

  line1: {
    height: 2,
    width: '100%',
    backgroundColor: '#D5A253',
    position: 'absolute',
    bottom: '0%',
  },
  line2: {
    height: '50%',
    width: 2,
    backgroundColor: '#D5A253',
    marginTop: 15,
    marginLeft: '1%',
    marginRight: '1%',
  },
  text1: {
    color: '#E5E5E5',
    fontSize: 17,
    fontWeight: '700',
  },
  text2: {
    color: '#D5A253',
    fontSize: 16,
    fontWeight: '700',
  },
  text3: {
    color: '#E5E5E5',
    fontSize: 14,
    fontWeight: '600',
  },
  text4: {
    position: 'absolute',
    color: '#e5e5e5',
    fontSize: 18,
    fontWeight: '600',
  },
  text5: {
    color: '#d0cece',
    fontSize: 22,
    fontWeight: '800',
  },
  text6: {
    overflow: 'hidden',
    color: '#D5A253',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 5,
  },
  text11: {
    color: '#E5E5E5',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 5,
    marginBottom: 5,
  },
  text7: {
    overflow: 'hidden',
    color: '#D5A253',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 5,
    marginLeft: 5,
    marginBottom: 5,
  },
  text8: {
    color: '#E5E5E5',
    fontSize: 13,
    fontWeight: '500',
    marginLeft: 5,
    marginBottom: 5,
  },
  text9: {
    color: 'gray',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 5,
  },
  text10: {
    color: '#fa7883',
    fontSize: 25,
    fontWeight: '800',
    marginTop: 5,
  },
  text12: {
    color: '#D5A253',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 20,
    marginLeft: 20,
  },
  img1: {
    height: 30,
    width: 30,
    tintColor: '#936A4A',
  },
  img2: {
    height: 30,
    width: 30,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    tintColor: '#936A4A',
  },
  input1: {
    height: 40,
    width: '80%',
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    marginTop: '15%',
    textAlign: 'center',
    alignSelf: 'center',
    color: '#E5E5E5',
    fontSize: 18,
  },
  btn1: {
    height: 50,
    width: '70%',
    backgroundColor: '#936A4A',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '15%',
    alignSelf: 'center',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    borderRadius: 50,
    marginBottom: 50,
    //elevation: 8,
  },
  checkbox3: {
    width: 100,
  },

  view18: {
    width: '90%',
    height: 40,
    flexDirection: 'row',
    marginLeft: 20,
    marginBottom: 10,
    marginTop: 20,
  },
  checkboxtext: {
    color: '#E5E5E5',
    fontSize: 16,
    fontWeight: '600',
  },
  img3: {
    width: 25,
    height: 25,
    tintColor: '#936A4A',
  },
  nextBtntext: {
    color: '#E5E5E5',
    fontSize: 17,
    fontWeight: '700',
  },
  btnsave: {
    width: '70%',
    height: 45,
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    marginBottom: 50,
    //elevation: 8,
  },
  CancleboostItemModel: {
    color: '#E5E5E5',
    fontSize: 20,
    fontWeight: '800',
  },
  heading1: {
    color: '#D5A253',
    fontSize: RFValue(25),
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 30,
  },
  heading2: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '600',
  },
  heading3: {
    color: '#E5E5E5',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 20,
  },
  heading4: {
    color: '#D5A253',
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
});
