import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },
  view2: {},

  view3: {
    width: 120,
    height: 120,
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: '#e5e5e5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dot1: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: 'gray',
    marginRight: 5,
  },
  dot2: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: '#d0cece',
    marginRight: 5,
  },
  view4: {
    width: '100%',
    height: 50,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  view5: {
    width: '100%',
    height: 50,
    marginTop: 20,
    flexDirection: 'row',
  },
  view6: {
    width: '100%',
    height: 100,
    marginTop: 10,
    flexDirection: 'row',
  },
  view7: {
    width: '50%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view8: {
    width: '100%',
    height: 30,
    flexDirection: 'row',
    marginLeft: 20,
    marginTop: 20,
  },
  view9: {
    width: '100%',
    height: 60,
    flexDirection: 'row',
    marginLeft: 20,
    marginBottom: 10,
    marginTop: 20,
  },
  view10: {
    width: '100%',
    marginLeft: 20,
    marginBottom: 10,
  },
  text1: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    alignSelf: 'center',
    textAlign: 'center',
    width: '70%',
    marginTop: 20,
  },
  text2: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    width: '70%',
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 10,
  },
  text3: {
    color: '#D5A253',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 20,
    marginLeft: 20,
  },
  text4: {
    color: '#d0cece',
    fontSize: 18,
    fontWeight: '600',
  },
  text5: {
    color: '#d0cece',
    fontSize: 20,
    fontWeight: '600',
  },
  text6: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    marginLeft: 20,
  },
  text7: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 20,
    textAlign: 'center',
  },
  img1: {
    width: '90%',
    height: '90%',
    borderRadius: 45,
    alignSelf: 'center',
  },
  plusBtn: {
    position: 'absolute',
    right: '0%',
    bottom: -10,
  },
  plusBtntext: {
    color: '#936A4A',
    fontSize: 50,
    fontWeight: '800',
  },
  nextBtn: {
    height: 50,
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 50,
    marginBottom: 20,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  nextBtntext: {
    color: '#e5e5e5',
    fontSize: 20,
    fontWeight: '800',
  },
  input1: {
    height: 50,
    width: '90%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    alignSelf: 'center',
    fontSize: 18,
    marginTop: 20,
    textAlign: 'center',
    color: '#e5e5e5',
  },
  input2: {
    height: 50,
    width: '90%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    alignSelf: 'center',
    fontSize: 18,
    marginTop: 10,
    textAlign: 'center',
    color: '#e5e5e5',
  },
  input3: {
    height: 100,
    width: '90%',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    textAlignVertical: 'top',
    alignSelf: 'center',
    color: '#e5e5e5',
    fontSize: 18,
  },
  input4: {
    height: 50,
    width: '30%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    alignSelf: 'center',
    fontSize: 18,
    textAlign: 'center',
    marginLeft: 20,
    color: '#e5e5e5',
  },
  input5: {
    height: 50,
    width: '70%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    alignSelf: 'center',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 10,
    color: '#e5e5e5',
  },
  img2: {
    width: 30,
    height: 30,
    tintColor: '#936A4A',
  },
  checkboxtext: {
    color: '#e5e5e5',
    fontWeight: '600',
  },
  checkbox: {
    width: 80,
    marginTop: 20,
  },

  checkbox1: {
    width: '80%',
    marginTop: 20,
  },
  checkbox3: {
    width: 120,
  },
  checkbox2: {
    width: '100%',
    marginLeft: 10,
    marginTop: 10,
  },
  checkboxtext2: {
    color: '#e5e5e5',
    fontWeight: '600',
  },
  btnsave: {
    height: 60,
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  timePickerStyle: {
    backgroundColor: 'white',
    width: '100%',
    borderTopWidth: 1,
    borderColor: 'gray',
    position: 'absolute',
    bottom: 0,
  },
  donebtnText: {
    color: '#936A4A',
    fontSize: 20,
    fontWeight: '800',
  },
  donebtn: {
    width: 60,
    height: 30,
    marginTop: 10,
    marginLeft: 10,
  },
  pickerStyle: {
    width: '100%',
    color: '#344953',
    justifyContent: 'center',
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
});
