import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },
  Heading1View: {
    height: '10%',
    width: '100%',
    marginTop: '3%',
    marginBottom: '3%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  Heading2View: {
    height: '90%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view2: {
    height: '80%',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view3: {
    width: '100%',
    alignItems: 'center',
  },
  text1: {
    color: '#D5A253',
    fontSize: 25,
    fontWeight: '700',
    alignSelf: 'center',
  },
  input1: {
    //height: 50,
    height: '11%',
    width: '90%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    marginBottom: '4%',
    fontSize: 18,
    color: '#e5e5e5',
  },
  view7: {
    width: '90%',
  },
  view22: {
    height: '30%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '5%',
  },
  img11: {
    height: '100%',
    width: '80%',
  },
  TCView1: {
    height: '10%',
    width: '100%',
    backgroundColor: 'gray',
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
  },
  TCView2: {
    //height: 330,
    height: '65%',
    width: '90%',
    marginTop: 15,
    borderBottomWidth: 0.5,
    borderColor: '#D5A253',
  },
  TCView3: {
    height: '95%',
    width: '95%',
    marginBottom: 5,
  },
  TCView4: {
    height: '100%',
    width: '50%',
    backgroundColor: '#936A4A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  TCView5: {
    height: 40,
    //height: '10%',
    width: '90%',
    marginTop: 20,
  },
  img1: {
    height: 20,
    width: 20,
    tintColor: '#936A4A',
  },
  checkbox: {
    width: '100%',
  },
  checkboxtext: {
    color: '#e5e5e5',
    fontSize: 16,
    fontWeight: '600',
  },
  btn1: {
    height: '12%',
    width: '60%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    //marginTop: '2%',
    alignSelf: 'center',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  btn1text: {
    color: '#e5e5e5',
    fontSize: 20,
    fontWeight: '700',
    position: 'absolute',
  },
  view5: {
    height: '15%',
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '2%',
    marginBottom: 30,
  },
  text3: {
    color: '#D5A253',
    fontSize: 16,
    fontWeight: '500',
    alignSelf: 'center',
  },
  text4: {
    color: '#936A4A',
    fontSize: 18,
    fontWeight: '500',
    alignSelf: 'center',
    marginLeft: 5,
    textDecorationLine: 'underline',
  },
  text5: {
    color: '#D5A253',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  text6: {
    color: '#936A4A',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  TCtext1: {
    color: '#D5A253',
    fontSize: 20,
    fontWeight: '600',
    marginTop: '5%',
  },
  TCtext2: {
    color: '#e5e5e5',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'justify',
  },
  TCtext3: {
    color: '#e5e5e5',
    fontSize: 17,
    fontWeight: '600',
  },
  TCtext4: {
    color: 'gray',
    fontSize: 17,
    fontWeight: '600',
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
});
