import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#2B3252',
  },
  view2: {
    height: '40%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '10%',
  },
  view3: {
    height: '60%',
    width: '100%',
    alignItems: 'center',
  },
  view4: {
    //height: 20,
    height: '7%',
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 50,
  },
  view5: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  img1: {
    height: 200,
    width: '80%',
  },
  input1: {
    height: '15%',
    width: '80%',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
    marginBottom: 20,
    fontSize: 18,
    color: '#e5e5e5',
  },
  btn1: {
    height: '15%',
    width: '70%',
    backgroundColor: '#936A4A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '10%',
    shadowOffset: { width: 8, height: 8 },
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 5,
    //elevation: 8,
  },
  btn1text: {
    position: 'absolute',
    color: '#e5e5e5',
    fontSize: 20,
    fontWeight: '700',
  },
  text1: {
    color: '#D5A253',
    fontSize: 16,
    fontWeight: '500',
    alignSelf: 'center',
  },
  text2: {
    color: '#936A4A',
    fontSize: 18,
    fontWeight: '500',
    alignSelf: 'center',
    marginLeft: 5,
  },
  indicator: {
    flex: 1,
    backgroundColor: '#2B3252',
    justifyContent: 'center',
    flexDirection: 'column',
  },
});
